name: Update all keys

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  orbitprod:
    uses: ./.github/workflows/update-keys.yml
    with:
      HOST: orbitprod
    secrets:
      KEY_PRIVATE: ${{ secrets.KEY_PRIVATE }}

  web-taket-server:
    uses: ./.github/workflows/update-keys.yml
    with:
      HOST: web-taket-server
    secrets:
      KEY_PRIVATE: ${{ secrets.KEY_PRIVATE }}
